# Form implementation generated from reading ui file 'DataViewerUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DataViewer(object):
    def setupUi(self, DataViewer):
        DataViewer.setObjectName("DataViewer")
        DataViewer.resize(402, 501)
        self.cmdSendToPlotpage = QtWidgets.QPushButton(parent=DataViewer)
        self.cmdSendToPlotpage.setGeometry(QtCore.QRect(230, 140, 101, 24))
        self.cmdSendToPlotpage.setObjectName("cmdSendToPlotpage")
        self.labelSelectAnItem = QtWidgets.QLabel(parent=DataViewer)
        self.labelSelectAnItem.setGeometry(QtCore.QRect(10, 210, 91, 16))
        self.labelSelectAnItem.setObjectName("labelSelectAnItem")
        self.cmdClose = QtWidgets.QPushButton(parent=DataViewer)
        self.cmdClose.setGeometry(QtCore.QRect(320, 470, 75, 24))
        self.cmdClose.setObjectName("cmdClose")
        self.comboBoxTargetFitpage = QtWidgets.QComboBox(parent=DataViewer)
        self.comboBoxTargetFitpage.setGeometry(QtCore.QRect(230, 40, 101, 22))
        self.comboBoxTargetFitpage.setObjectName("comboBoxTargetFitpage")
        self.labelSendToFitpage = QtWidgets.QLabel(parent=DataViewer)
        self.labelSendToFitpage.setGeometry(QtCore.QRect(230, 10, 161, 21))
        self.labelSendToFitpage.setObjectName("labelSendToFitpage")
        self.labelSubtab = QtWidgets.QLabel(parent=DataViewer)
        self.labelSubtab.setGeometry(QtCore.QRect(230, 70, 161, 21))
        self.labelSubtab.setObjectName("labelSubtab")
        self.comboBoxTargetSubtab = QtWidgets.QComboBox(parent=DataViewer)
        self.comboBoxTargetSubtab.setGeometry(QtCore.QRect(230, 100, 101, 22))
        self.comboBoxTargetSubtab.setObjectName("comboBoxTargetSubtab")

        self.retranslateUi(DataViewer)
        QtCore.QMetaObject.connectSlotsByName(DataViewer)

    def retranslateUi(self, DataViewer):
        _translate = QtCore.QCoreApplication.translate
        DataViewer.setWindowTitle(_translate("DataViewer", "Form"))
        self.cmdSendToPlotpage.setText(_translate("DataViewer", "Send to Plotpage"))
        self.labelSelectAnItem.setText(_translate("DataViewer", "No item selected"))
        self.cmdClose.setText(_translate("DataViewer", "Close"))
        self.labelSendToFitpage.setText(_translate("DataViewer", "Send to Plot from Fitpage..."))
        self.labelSubtab.setText(_translate("DataViewer", "Display in Subtab..."))
