# Form implementation generated from reading ui file 'DataViewerDialogUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DataViewerDialog(object):
    def setupUi(self, DataViewerDialog):
        DataViewerDialog.setObjectName("DataViewerDialog")
        DataViewerDialog.resize(279, 247)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DataViewerDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 210, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.listToFitpage = QtWidgets.QListWidget(parent=DataViewerDialog)
        self.listToFitpage.setGeometry(QtCore.QRect(10, 10, 256, 192))
        self.listToFitpage.setObjectName("listToFitpage")
        self.cbSubtab = QtWidgets.QComboBox(parent=DataViewerDialog)
        self.cbSubtab.setGeometry(QtCore.QRect(190, 215, 71, 21))
        self.cbSubtab.setObjectName("cbSubtab")

        self.retranslateUi(DataViewerDialog)
        self.buttonBox.accepted.connect(DataViewerDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(DataViewerDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DataViewerDialog)

    def retranslateUi(self, DataViewerDialog):
        _translate = QtCore.QCoreApplication.translate
        DataViewerDialog.setWindowTitle(_translate("DataViewerDialog", "Dialog"))
