# Form implementation generated from reading ui file 'FitPageUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fitPageWidget(object):
    def setupUi(self, fitPageWidget):
        fitPageWidget.setObjectName("fitPageWidget")
        fitPageWidget.resize(400, 300)
        self.doubleSpinBox_a = QtWidgets.QDoubleSpinBox(parent=fitPageWidget)
        self.doubleSpinBox_a.setGeometry(QtCore.QRect(40, 40, 62, 22))
        self.doubleSpinBox_a.setMinimum(-5.0)
        self.doubleSpinBox_a.setMaximum(5.0)
        self.doubleSpinBox_a.setProperty("value", 1.0)
        self.doubleSpinBox_a.setObjectName("doubleSpinBox_a")
        self.doubleSpinBox_b = QtWidgets.QDoubleSpinBox(parent=fitPageWidget)
        self.doubleSpinBox_b.setGeometry(QtCore.QRect(40, 80, 62, 22))
        self.doubleSpinBox_b.setMinimum(-5.0)
        self.doubleSpinBox_b.setMaximum(5.0)
        self.doubleSpinBox_b.setProperty("value", 1.0)
        self.doubleSpinBox_b.setObjectName("doubleSpinBox_b")
        self.label_a = QtWidgets.QLabel(parent=fitPageWidget)
        self.label_a.setGeometry(QtCore.QRect(20, 40, 16, 16))
        self.label_a.setObjectName("label_a")
        self.label_b = QtWidgets.QLabel(parent=fitPageWidget)
        self.label_b.setGeometry(QtCore.QRect(20, 80, 16, 16))
        self.label_b.setObjectName("label_b")
        self.label_equation = QtWidgets.QLabel(parent=fitPageWidget)
        self.label_equation.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label_equation.setObjectName("label_equation")

        self.retranslateUi(fitPageWidget)
        QtCore.QMetaObject.connectSlotsByName(fitPageWidget)

    def retranslateUi(self, fitPageWidget):
        _translate = QtCore.QCoreApplication.translate
        fitPageWidget.setWindowTitle(_translate("fitPageWidget", "Form"))
        self.label_a.setText(_translate("fitPageWidget", "A"))
        self.label_b.setText(_translate("fitPageWidget", "B"))
        self.label_equation.setText(_translate("fitPageWidget", "Parameters for f(x)=a*exp(b*x)"))
