# Form implementation generated from reading ui file 'MainWindowUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 700)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cmdCreatePlot = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cmdCreatePlot.setGeometry(QtCore.QRect(570, 630, 121, 24))
        self.cmdCreatePlot.setObjectName("cmdCreatePlot")
        self.cbData = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.cbData.setGeometry(QtCore.QRect(570, 510, 120, 20))
        self.cbData.setObjectName("cbData")
        self.cbFit = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.cbFit.setGeometry(QtCore.QRect(570, 540, 120, 20))
        self.cbFit.setObjectName("cbFit")
        self.cbResiduals = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.cbResiduals.setGeometry(QtCore.QRect(570, 570, 120, 20))
        self.cbResiduals.setObjectName("cbResiduals")
        self.labelWarning = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelWarning.setGeometry(QtCore.QRect(570, 590, 121, 31))
        self.labelWarning.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.labelWarning.setObjectName("labelWarning")
        self.fittingTabs = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.fittingTabs.setGeometry(QtCore.QRect(10, 10, 681, 471))
        self.fittingTabs.setObjectName("fittingTabs")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menubar.setObjectName("menubar")
        self.menuFitPages = QtWidgets.QMenu(parent=self.menubar)
        self.menuFitPages.setObjectName("menuFitPages")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewFitPage = QtGui.QAction(parent=MainWindow)
        self.actionNewFitPage.setObjectName("actionNewFitPage")
        self.menuFitPages.addAction(self.actionNewFitPage)
        self.menubar.addAction(self.menuFitPages.menuAction())

        self.retranslateUi(MainWindow)
        self.fittingTabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cmdCreatePlot.setText(_translate("MainWindow", "Create Plot"))
        self.cbData.setText(_translate("MainWindow", "Plot Data"))
        self.cbFit.setText(_translate("MainWindow", "Plot Fit"))
        self.cbResiduals.setText(_translate("MainWindow", "Plot Residuals"))
        self.labelWarning.setText(_translate("MainWindow", "Select atleast one box"))
        self.menuFitPages.setTitle(_translate("MainWindow", "Fit Pages"))
        self.actionNewFitPage.setText(_translate("MainWindow", "New Fit Page"))
